version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
  pre_build:
    commands:
      - java -version
      - mvn --version
      - echo "Installing dependencies..."
      - mvn clean install
  build:
    commands:
      - echo "Running SCA - OWASP Dependency Check..."
      - mvn org.owasp:dependency-check-maven:check
      - echo "Building the WAR file..."
      - mvn package
      - echo "Running JaCoCo Code Coverage..."
      - mvn test jacoco:report
      - echo "Running SonarQube Analysis..."
      - mvn sonar:sonar -Dsonar.token=$SONAR_TOKEN
  post_build:
    commands:
      - echo "Build and Security Analysis Completed!"

artifacts:
  files:
    - target/*.war
    - target/site/jacoco/index.html
    - target/dependency-check-report.html
  discard-paths: yes
