version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Setting up environment variables"
      - mvn clean
  build:
    commands:
      - echo "Running Unit Tests and JaCoCo"
      - mvn test
      - echo "Running Static Code Analysis with SonarCloud"
      - mvn sonar:sonar -Dsonar.organization=$SONAR_ORG -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      - echo "Running OWASP Dependency Check"
      - mvn org.owasp:dependency-check-maven:check
  post_build:
    commands:
      - echo "Build, Security Analysis, and Tests Completed"
      - echo "Generating Reports"
artifacts:
  files:
    - target/*.war
    - target/site/jacoco/index.html
    - target/dependency-check-report.html
