version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java 17"
      - java -version
      - mvn --version
      - echo "Retrieving NVD API Key from SSM..."
      - export NVD_API_KEY=$(aws ssm get-parameter --name "/NVD_API_KEY" --with-decryption --query "Parameter.Value" --output text)
      
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn clean install
      
  build:
    commands:
      - echo "Running SCA - OWASP Dependency Check..."
      - mvn org.owasp:dependency-check-maven:check
      - echo "Building the WAR file..."
      - mvn package
      - echo "Running JaCoCo Code Coverage..."
      - mvn test jacoco:report
      - echo "Running SonarQube Analysis..."
      - mvn sonar:sonar -Dsonar.token=$SONAR_TOKEN
      
  post_build:
    commands:
      - echo "Build and Security Analysis Completed!"

artifacts:
  files:
    - target/*.war
    - target/site/jacoco/index.html
    - target/dependency-check-report.html
  discard-paths: yes
